### ISSUE TITLE
Use case

### ISSUE THREAD

**Issue by KudelinRoman** [KudelinRoman/Course-project-UML-TRPO#45]
Загрузить сюда Use case

**Comment by KudelinRoman** [comment]
![image](https://user-images.githubusercontent.com/47320335/59678030-fff6c480-91d3-11e9-8065-3fd546678077.png)

**Comment by MaximTrapeznikov** [comment]
![image](https://user-images.githubusercontent.com/46522172/59866773-1435ef80-9395-11e9-9f81-af865d80fb4d.png)
